In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr2 = np.array(my_mat)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.8138122 , 0.77360338, 0.51455891, 0.74132522, 0.26383271])

In [23]:
np.random.rand(5,5)

array([[0.79926978, 0.10003876, 0.53113293, 0.72883141, 0.27299126],
       [0.08675261, 0.61617216, 0.18175088, 0.1680813 , 0.92583889],
       [0.14430506, 0.60274434, 0.20306324, 0.85046417, 0.78276972],
       [0.72139802, 0.21629061, 0.29785358, 0.9328861 , 0.25404988],
       [0.7322909 , 0.00607385, 0.5420044 , 0.86217175, 0.61995581]])

In [54]:
np.random.randn(2,2)

array([[-1.08575362,  0.26728193],
       [ 2.6541391 ,  1.30946613]])

In [34]:
np.random.randint(1,100)

70

In [37]:
np.random.randint(1,100,10)

TypeError: Cannot interpret '2' as a data type

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([40,  7,  2, 24, 35,  5,  3, 16, 17, 25])

In [52]:
arr =arr.reshape(5,5)

In [43]:
ranarr.max()

40

In [44]:
ranarr.min()

2

In [45]:
ranarr

array([40,  7,  2, 24, 35,  5,  3, 16, 17, 25])

In [46]:
ranarr.argmax()

0

In [47]:
ranarr[0]

40

In [48]:
ranarr.argmin()

2

In [49]:
ranarr[2]

2

In [53]:
arr.shape

(5, 5)

In [56]:
arr.dtype

dtype('int32')

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[1]

1

In [61]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[0:1000]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
slice_of_arr = arr[0:6]

In [65]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
arr_copy = arr[0:6].copy()

In [68]:
arr_copy

array([0, 1, 2, 3, 4, 5])

In [70]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[1][1]

25

In [75]:
arr_2d[2][1]

40

In [76]:
arr_2d[2,1]

40

In [77]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [79]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [80]:
arr = np.arange(0,11)

In [83]:
bool_arr = arr>5

In [84]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [85]:
bool_arr = arr <3

In [86]:
arr[bool_arr]

array([0, 1, 2])

In [87]:
arr_2d = np.arange(0,50).reshape(5,10)

In [88]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [90]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [91]:
arr = np.arange(0,11)

In [92]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [93]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [96]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [97]:
arr-100


array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [99]:
arr/arr

<ipython-input-99-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [103]:
np.max(arr)

10

In [104]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])